services:
  - type: web
    name: kumaravel-loomflow-server
    runtime: node
    plan: free
    region: singapore
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://kumaravel-vendor-management-system.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
